### ISSUE TITLE
Issue on Deploy in Heroku when ENV = development

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#443]
When trying to deploy to Heroku and the environment = development, we are getting the following error:

````
rake aborted!
NameError: uninitialized constant Annotate
/app/lib/tasks/auto_annotate_models.rake:33:in `<top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.7/lib/rails/engine.rb:654:in `block in run_tasks_blocks'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.7/lib/rails/engine.rb:654:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.7/lib/rails/engine.rb:654:in `run_tasks_blocks'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.7/lib/rails/application.rb:384:in `run_tasks_blocks'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.7/lib/rails/engine.rb:449:in `load_tasks'
/app/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)
````

Stack knows more about this, but it needs to be fixed.

**Comment by mafernando** [comment]
@chriskacerguis - Could provide me some instructions regarding how to reproduce this issue?

I was able to manually deploy this from Heroku on `jellyfish-core-dev` under the GitHub deployment settings:

![image](https://cloud.githubusercontent.com/assets/9356425/6906294/9916057c-d6f3-11e4-86b1-533503a707d1.png)

![image](https://cloud.githubusercontent.com/assets/9356425/6906273/7bad1052-d6f3-11e4-9a6c-bbdbb631af7f.png)

and get a Build succeeded without any error in the build log about Annotate. 

Can't figure out where the above error is getting thrown.

**Comment by mafernando** [comment]
See this [example log](https://dashboard.heroku.com/apps/jellyfish-core-dev/activity/builds/8ffa0ea9-f591-4c0b-84bc-d7b055f5a97d) containing aforementioned error.

**Comment by mafernando** [comment]
##### @chriskacerguis - I've summarized my findings on why Annotate is breaking on Heroku when deployed in development mode below.

The gems specified in the [development and test](https://github.com/projectjellyfish/api/blob/master/Gemfile#L46) block of our Gemfile do not get loaded on Heroku. 

```ruby
# Tests
group :development, :test do
  gem 'annotate'
  gem 'awesome_print'
  gem 'brakeman', require: false
  gem 'codeclimate-test-reporter', require: nil
  gem 'database_cleaner', '~> 1.3.0'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'license_finder'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.0'
  gem 'rubocop'
  gem 'seed_dump'
  gem 'spring'
  gem 'web-console', '~> 2.0.0'
  gem 'capybara-webkit'
  gem 'capybara-angular'
  gem 'launchy'
```

Specifically, from Heroku's [devcenter](https://devcenter.heroku.com/articles/getting-started-with-rails4#troubleshooting):

<div style='center;'>
<table><tr><td><i>
If you’re missing a gem when you deploy, check your Bundler groups. Heroku builds your app without the development or test groups, and if your app depends on a gem from one of these groups to run, you should move it out of the group.
</i></tr></td><table>
</div>

I believe that the error occurring in our Heroku logs can be attributed to the fact that Heroku will always pass the `--without development:test` option to `bundle install` even when we try to deploy as *development* or *test*:

```
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.2.1
-----> Installing dependencies using 1.7.12
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Using rake 10.4.2
       ...
       Using devise 3.4.1
       Your bundle is complete!
       Gems in the groups development and test were not installed.
       It was installed into ./vendor/bundle
       Bundle completed (0.73s)
       Cleaning up the bundler cache.
       Could not detect rake tasks
       ensure you can run `$ bundle exec rake -P` against your app with no environment variables present
       and using the production group of your Gemfile.
       This may be intentional, if you expected rake tasks to be run
       cancel the build (CTRL+C) and fix the error then commit the fix:
       rake aborted!
        NameError: uninitialized constant Annotate
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/lib/tasks/auto_annotate_models.rake:33:in `<top (required)>'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/bundle/ruby/2.2.0/gems/railties-4.1.7/lib/rails/engine.rb:654:in `block in run_tasks_blocks'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/bundle/ruby/2.2.0/gems/railties-4.1.7/lib/rails/engine.rb:654:in `each'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/bundle/ruby/2.2.0/gems/railties-4.1.7/lib/rails/engine.rb:654:in `run_tasks_blocks'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/bundle/ruby/2.2.0/gems/railties-4.1.7/lib/rails/application.rb:384:in `run_tasks_blocks'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/bundle/ruby/2.2.0/gems/railties-4.1.7/lib/rails/engine.rb:449:in `load_tasks'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/Rakefile:7:in `<top (required)>'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
       /tmp/build_09148d743da312a9906ddc7961187b23/projectjellyfish-api-fcfc53b/vendor/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
       vendor/bundle/bin/rake:16:in `load'
       vendor/bundle/bin/rake:16:in `<main>'

-----> Discovering process types
       Procfile declares types -> web
       Default types for Ruby  -> console, rake, worker

-----> Compressing... done, 37.7MB
-----> Launching... done, v299
       https://jellyfish-core-dev.herokuapp.com/ deployed to Heroku
```

Jellyfish will still attempt to load the *development* tasks in its path, such as [`Annotate.load_tasks`](https://github.com/projectjellyfish/api/blob/master/lib/tasks/auto_annotate_models.rake#L33), but Rails will not recognize `Annotate` and throw a `NameError: uninitialized constant Annotate`

**Comment by mafernando** [comment]
PR https://github.com/projectjellyfish/api/pull/467 addresses this
