### ISSUE TITLE
Fix jellyfish-core-dev

### ISSUE THREAD

**Issue by calebthompson** [projectjellyfish/api#480]
500 on page load.

From @chriskacerguis: 

Got this in logs

```
2015-04-06T15:34:12.436495+00:00 heroku[web.2]: State changed from crashed to starting
2015-04-06T15:34:16.983738+00:00 heroku[web.2]: Starting process with command `bundle exec puma -C config/puma.rb`
2015-04-06T15:34:18.971882+00:00 app[web.2]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2015-04-06T15:34:18.971863+00:00 app[web.2]: fatal: Not a git repository (or any parent up to mount point /app)
2015-04-06T15:34:19.531154+00:00 app[web.2]: [3] * Version 2.11.1 (ruby 2.2.1-p85), codename: Intrepid Squirrel
2015-04-06T15:34:19.531140+00:00 app[web.2]: [3] Puma starting in cluster mode...
2015-04-06T15:34:19.531156+00:00 app[web.2]: [3] * Min threads: 8, max threads: 16
2015-04-06T15:34:19.531157+00:00 app[web.2]: [3] * Environment: development
2015-04-06T15:34:19.531159+00:00 app[web.2]: [3] * Process workers: 3
2015-04-06T15:34:19.531163+00:00 app[web.2]: [3] * Preloading application
2015-04-06T15:34:22.645244+00:00 app[web.2]: [3] ! Unable to load application: NameError: uninitialized constant Provisioner
2015-04-06T15:34:22.645341+00:00 app[web.2]:    from /app/config/environment.rb:2:in `<top (required)>'
2015-04-06T15:34:22.645259+00:00 app[web.2]: /app/lib/jellyfish_fog_aws/lib/jellyfish_fog_aws/databases.rb:4:in `<module:AWS>': uninitialized constant Provisioner (NameError)
2015-04-06T15:34:22.645283+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
2015-04-06T15:34:22.645287+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
2015-04-06T15:34:22.645346+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
2015-04-06T15:34:22.645264+00:00 app[web.2]:    from /app/lib/jellyfish_fog_aws/lib/jellyfish_fog_aws/databases.rb:3:in `<module:Fog>'
2015-04-06T15:34:22.645330+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
2015-04-06T15:34:22.645351+00:00 app[web.2]:    from config.ru:in `new'
2015-04-06T15:34:22.645268+00:00 app[web.2]:    from /app/lib/jellyfish_fog_aws/lib/jellyfish_fog_aws/databases.rb:2:in `<module:Jellyfish>'
2015-04-06T15:34:22.645336+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
2015-04-06T15:34:22.645357+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
2015-04-06T15:34:22.645272+00:00 app[web.2]:    from /app/lib/jellyfish_fog_aws/lib/jellyfish_fog_aws/databases.rb:1:in `<top (required)>'
2015-04-06T15:34:22.645289+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
2015-04-06T15:34:22.645349+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
2015-04-06T15:34:22.645275+00:00 app[web.2]:    from /app/lib/jellyfish_fog_aws/lib/jellyfish_fog_aws.rb:4:in `<top (required)>'
2015-04-06T15:34:22.645343+00:00 app[web.2]:    from config.ru:3:in `require'
2015-04-06T15:34:22.645362+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-2.11.1/lib/puma/configuration.rb:107:in `app'
2015-04-06T15:34:22.645278+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
2015-04-06T15:34:22.645345+00:00 app[web.2]:    from config.ru:3:in `block in <main>'
2015-04-06T15:34:22.645292+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
2015-04-06T15:34:22.645338+00:00 app[web.2]:    from /app/config/application.rb:8:in `<top (required)>'
2015-04-06T15:34:22.645356+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
2015-04-06T15:34:22.645366+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cluster.rb:301:in `run'
2015-04-06T15:34:22.645365+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-2.11.1/lib/puma/runner.rb:113:in `load_and_bind'
2015-04-06T15:34:22.645370+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cli.rb:512:in `run'
2015-04-06T15:34:22.645373+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-2.11.1/bin/puma:10:in `<top (required)>'
2015-04-06T15:34:22.645339+00:00 app[web.2]:    from /app/config/environment.rb:2:in `require'
2015-04-06T15:34:22.645360+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
2015-04-06T15:34:22.645352+00:00 app[web.2]:    from config.ru:in `<main>'
2015-04-06T15:34:22.645376+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/bin/puma:23:in `load'
2015-04-06T15:34:22.645380+00:00 app[web.2]:    from /app/vendor/bundle/ruby/2.2.0/bin/puma:23:in `<main>'
2015-04-06T15:34:23.577011+00:00 heroku[web.2]: State changed from starting to crashed
2015-04-06T15:34:23.566138+00:00 heroku[web.2]: Process exited with status 1
2015-04-06T15:34:29.860891+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=jellyfish-core-build.dpi.bah.com request_id=0015165e-64e3-4aae-81e8-de0afb713af7 fwd="67.79.8.125" dyno= connect= service= status=503 bytes=
```

**Comment by calebthompson** [comment]
This is unrelated to

**Comment by calebthompson** [comment]
It appears that heroku hasn't been updated in four months, which can't be right because of the error, but it's certainly very different than what we've been working with.

**Comment by chriskacerguis** [comment]
That doesn't seem right...I'm looking at the deploy logs, and it's been updating

**Comment by calebthompson** [comment]
still having trouble. I opened a heroku support ticket and I'll keep banging on it.
