### ISSUE TITLE
Deploy to Heroku post deploy script is failing

### ISSUE THREAD

**Issue by dthurston** [projectjellyfish/api#595]
I'm getting this error when I "deploy to Heroku"

```
rake aborted!
LoadError: cannot load such file -- capybara/poltergeist
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
/app/config/application.rb:8:in `<top (required)>'
/app/Rakefile:5:in `require'
/app/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by chriskacerguis** [comment]
That seemed to fix it (just tested and it deployed just fine)
